[phases.setup]
  nixpkgsArchive = "8e3b64db39f2aaa14b35ee5378378d627a594e15"
  nixPkgs = ["...", "python311"]

[phases.install]
  cmds = ["cd ai-analyzer && pip install -r requirements.txt"]

[phases.build]
  cmds = [":"]

[start]
  cmd = "cd ai-analyzer && uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
